### ISSUE TITLE
Hackport generates metadata.xml in wrong encoding

### ISSUE THREAD

**Issue by ahyangyi** [gentoo-haskell/hackport#31]
For example, it breaks repoman checks because clash happens to style itself as "CλaSH".

See the generated metadata.xml and fixed versions:
https://github.com/ahyangyi/ahyangyi-overlay/commit/d25e94cad82c83b8c173603926d95a8a37fc40a4

**Comment by trofi** [comment]
Yeah, I think it's a limitation of `xml` package (or our hackport's usage of it.

**Comment by solpeth** [comment]
This may be to do with us packing the `metadata.xml` into a `ByteString`: https://github.com/gentoo-haskell/hackport/blob/4cf105e5f1958d904bf367ee1402e76c24cc0d06/Merge.hs#L469 https://github.com/gentoo-haskell/hackport/blob/4cf105e5f1958d904bf367ee1402e76c24cc0d06/Merge.hs#L494-L499

Using `String`s rather than `ByteString`s generates the metadata for `clash-ghc` correctly, but it theoretically comes with a performance penalty (I haven't investigated more efficient alternatives, yet).

@trofi, any opinions on which way to go about this?

**Comment by trofi** [comment]
Using `String` should be fine as a fix. `metadata.xml` files are usually tiny. Longer term `Text` could be more practical way to handle workloads like that.

**Comment by solpeth** [comment]
Sounds good. I'll write it up using `Text` after work today.
