### ISSUE TITLE
Support hpack

### ISSUE THREAD

**Issue by crocket** [gentoo-haskell/hackport#46]
hpack compiles package.yaml into *.cabal

stack uses hpack to compile package.yaml into *.cabal

I want hackport to use package.yaml instead of *.cabal so that I don't have to put *.cabal into my repository.

**Comment by trofi** [comment]
hackport uses hackage's index directly. If hackage/Cabal supports `hpack` packages as-is we could extend hackport. otherwise I would suggest doing the following sequence:

- use `hpack` to generate `.cabal` file locally
- use `hackport make-ebuild` to generate `.ebuild`
- edit `src_prepare()` to update ebuild to create `.cabal` file as `haskell-cabal.eclass` uses Cabal to build packages. I guess Cabal does not support `.yaml` format.

**Comment by crocket** [comment]
Are you suggesting that I should manually modify ebuilds generated by hackport to account for hpack?

**Comment by trofi** [comment]
That's one possibility, yes.

**Comment by solpeth** [comment]
Closing. Happy to take a look at it in the future if things change regarding hackage and hpack.
