### ISSUE TITLE
Release v0.6 is missing from Hackage

### ISSUE THREAD

**Issue by Hypoon** [gentoo-haskell/hackport#51]
Perhaps I'm jumping the gun, but I see that version 0.5.6 was released on May 30th, 2018, and uploaded to hackage also on May 30th, 2018. Github tells me that version 0.6 was released 15 days ago, but I don't see it on hackage. I anticipate that this is also why it is not yet in portage.

Is there a specific reason for the delay?

**Comment by trofi** [comment]
Jack planned to get hackage account and upload it there. Might take a while.

**Comment by solpeth** [comment]
Sorry for the delay.

I have a hackage account, I'm just wondering if we will decide to:
a) follow the PVP as outlined in an email from a Hackage Trustee, but increasing the maintenance burden on us, or
b) upload it as is and see how we go.

Do you have any opinions on this @trofi?

**Comment by trofi** [comment]
I suggest uploading as-is.

**Comment by solpeth** [comment]
Sounds good. I will do this after work (approximately in 10 hours).

**Comment by solpeth** [comment]
@trofi do I need to be added to the hackport maintainer group to allow me to upload? If so, my username is the same as this one.

**Comment by Hypoon** [comment]
Why does following the PVP increase the maintenance burden?

I ask because deviating from a standard often creates headaches in the future.

**Comment by solpeth** [comment]
@hypoon one issue is having to actively maintain upper bounds on dependencies.

To my knowledge, one argument is that the PVP is supposed to allow software to be guaranteed buildable forever as per the dependency bounds set in the cabal file, as opposed to leaving the upper bounds off and allowing silent breakages to creep in as dependencies slowly bump their versions and make API changes over time. This relies on packages following the PVP in their versioning to signal API breakages.

But it means whenever a dependency's major version is bumped, hackport's dependency bounds will need to be updated to allow building with the newer versions of those dependencies, even if they will likely work.

**Comment by Hypoon** [comment]
Thank you for the explanation, but I'm afraid I still don't understand.

I thought PVP was about other packages depending on hackport, and that "following PVP" just tells you how to choose the new version number for your new release. Then other packages can use hackport's new version number to predict whether there will be a problem.

Needing to maintain upper bounds on hackport's dependencies sounds like a question of whether hackport's dependencies follow PVP, which is out of your control, right? I don't understand how deciding whether to follow PVP (to choose hackport's new version number) changes whether the hackport maintainers need to check the dependencies.

**Comment by solpeth** [comment]
Sorry for my lazy explanation, I appreciate how it wasn't consistent or clear enough. There's a bit more information at https://hackage.haskell.org/upload#versioning_and_curation. I can try to explain in greater detail later tonight, after work, if need be.

**Comment by Hypoon** [comment]
I see this section:

"In order to ensure the integrity and well-functioning of the Hackage/Cabal ecosystem, all curated packages should follow Haskell's Package Versioning Policy (PVP)."

So, curated packages should follow PVP, but it doesn't say that packages which follow PVP should be curated.

Honestly, I'm considering using Haskell for a large project of my own soon. Versioning and dependency nightmares are pushing me toward doing the project in C instead. This is why I care... I'm not trying to convince you guys to use PVP, I just want to understand as much as possible so I can make the most educated decision that I can.

Somewhat off-topic, I'm very grateful for the work everyone does to help Haskell play nice in Gentoo. I attribute these issues to growing pains, and I sincerely hope that some day we won't need haskell-updater anymore. I don't like using language-specific package managers (python, nodejs, I'm looking at you too...!), and I especially don't like needing dependency-tree sandboxes for every project. I love Haskell, but I despise the infrastructure (although hackage is awesome for documentation). Once I finish my schooling, I hope to contribute more. Until then, I try to help by filing bug reports whenever I notice things (...such as hackport failing to build because GHC updated before hackport 0.6 hit portage. Would an upper bound on a dependency version have prevented this?).

**Comment by trofi** [comment]
> @trofi do I need to be added to the hackport maintainer group to allow me to upload?
Yes. I've added you as: http://hackage.haskell.org/package/hackport/maintainers/

**Comment by trofi** [comment]
> Why does following the PVP increase the maintenance burden?
> 
> I ask because deviating from a standard often creates headaches in the future.

PVPs ideas are good:

1. version the packages the way users can infer likely breakages just by looking at version numbers
2. depend only on known-working versions

But I don't think implementation is working at scale. [1.] is nice: you can worry less about minor bumps.

[2.] means constant update of `.cabal` files when major version of a package comes in hackage-wide. Upstream Hackage maintainers just don't to it diligently and Gentoo ends up patching them downstream. There are 750 instances of patching in ::haskell overlay: https://github.com/gentoo-haskell/gentoo-haskell/search?q=cabal_chdeps&unscoped_q=cabal_chdeps . ::haskell contains 3500 ebuilds. 21% of all ebuilds requires manual patching.

It's including the fact that we try hard to send these version bumps upstream and usually don't keep old versions around.

This means ::haskell is usually running different (usually newer) version of software than anyone else. This makes upstreaming fixes harder because everybody is on an older version and is yet to see breakage. I would say that it's a sign of ecosystem breakdown and maintenance fragmentation downstream.

I personally think that presence of upper bounds in `.cabal` files causes more damage than good longer term. In haskell world unmaintained packages break very soon anyways. But it's not a very popular opinion :)

**Comment by trofi** [comment]
> Honestly, I'm considering using Haskell for a large project of my own soon. Versioning and dependency nightmares are pushing me toward doing the project in C instead. This is why I care... I'm not trying to convince you guys to use PVP, I just want to understand as much as possible so I can make the most educated decision that I can.

As hackport does not expose a library PVP is not a large issue here. We are ready to fix any breakages done by dependencies.

> I attribute these issues to growing pains, and I sincerely hope that some day we won't need haskell-updater anymore.

That is arguably a Gentoo bug: https://github.com/gentoo-haskell/gentoo-haskell/issues/199 . We see it occasionally in C land as well: https://wiki.gentoo.org/wiki/Mpfr4-update-guide . C projects are lucky not to have too deep dependency tree.

> Until then, I try to help by filing bug reports whenever I notice things (...such as hackport failing to build because GHC updated before hackport 0.6 hit portage. Would an upper bound on a dependency version have prevented this?).

Depends on your goal. Would you rather not upgrade GHC to get hackport working? If the answer is yes, then yes, PVP would have prevented this breakage.

**Comment by orlitzky** [comment]
> Honestly, I'm considering using Haskell for a large project of my own soon. Versioning and dependency nightmares are pushing me toward doing the project in C instead. This is why I care... I'm not trying to convince you guys to use PVP, I just want to understand as much as possible so I can make the most educated decision that I can.

This is a tough call to make. The Haskell ecosystem is focused on making software easier to write, not easier to use and deploy. The standard is not standard any more, and fundamental bits of the language (string processing, http requests) can change incompatibly almost daily. The PVP, Hackage, and the two most common build systems only exacerbate the problem and encourage bad practices. 

For example, we knew a long time ago that testing for a specific version of a library was the wrong thing to do. Instead, you should test for the existence of a function in the API. In other words, you should test for what you use, rather than an arbitrary number that you think is correlated with what you use. Testing for the version number means that your bounds will be too strict, which means that you need to bundle everything if you want to install more than one Haskell program. This in turn leads to people being willing to completely break critical packages, with the justification that "everyone should be using stack with known version bounds anyway." The cycle perpetuates itself.

The C language is a lot more mature in that sense... there's a big boring committee that needs to meet for years if they want to break your programs. Libraries do change, but if a major C library breaks its API once a week, then people simply won't use it. And maybe more importantly: so long as they don't break the _entire_ API, you can use autotools to test for the part that you use. I think you spend more time solving "real" problems in C.

On the other hand, system administration is more fun when the programs that you deploy actually work. And Haskell programs are a lot more likely to work. In my opinion, they're also more fun to write, which leads to higher-quality code. So long as you stick to a small number of old and boring dependencies, the versioning problem actually isn't all that bad. And of course, Gentoo makes everything much, much easier.

**Comment by dorrellmw** [comment]
There's still one piece of the puzzle that doesn't make sense to me. What stops you from using PVP to choose your version number, but continuing to omit upper bounds on your dependencies?

Is there an actual option where you tell Hackage "yes, this uses PVP", and it then forces you to add dependency bounds?

**Comment by orlitzky** [comment]
> There's still one piece of the puzzle that doesn't make sense to me. What stops you from using PVP to choose your version number, but continuing to omit upper bounds on your dependencies?

Nothing, really. The numbering scheme portion of the PVP is fine in isolation. But in practice, everyone else uses SemVer and understands SemVer. And many Haskell packages that claim to use the PVP actually are using something isomorphic to SemVer, because the first component in PVP's `MAJOR.MAJOR.MINOR.PATCH` scheme is fixed.

I stick to SemVer in my own projects. You might be able to convince me that PVP is better, but you won't convince me that it's _so much better_ that I should fork the version numbering scheme that the rest of the world uses. 

And like trofi said, the PVP is aimed mostly at libraries (whose consumers will care about API breakage), and not end-user applications like hackport. No one needs to worry (yet) about what data types or function signatures have changed between versions of hackport.
