### ISSUE TITLE
How to correctly handle stackage lts resolver

### ISSUE THREAD

**Issue by Uroc327** [gentoo-haskell/hackport#64]
As far as I can see, hackport does not respect the `resolver` field in the `stack.yaml`. I think, this can lead to version incompatibilities.

See for example [monad-logger](https://hackage.haskell.org/package/monad-logger), which depends on `unliftio-core`. Its `package.yaml` does not specify any particular version. The `stack.yaml`, though, specifies `lts-14.22` and thus `unliftio-core-0.1.2.0`.

The latest version is `unliftio-core-0.2.0.1`. But this version introduced breaking changes. So now, when trying to build `monad-logger` against the latest `unliftio-core`, the build fails (due to `askUnliftIo` not being a method of class `MonadUnliftIO` any longer).

What is the correct way to ensure version compatibilities here?

**Comment by trofi** [comment]
Hackport only considers `.cabal` files and uses `hackage` database. It does not use `stackage` snapshots. 

It by design leads to occasional failures. `::haskell` maintainers normally build most of overlay and see what breakages exist there and try to port most of them to latest versions if possible. Ideally port upstream as well.

That way we can get hackage state that mostly works.

**Comment by Uroc327** [comment]
I see, thanks.
