### ISSUE TITLE
hackport consumes all RAM handling deepseq-bounded

### ISSUE THREAD

**Issue by l29ah** [gentoo-haskell/hackport#78]
https://hackage.haskell.org/package/deepseq-bounded
```
There are up to 4194304 possible flag combinations.
This may take a while.
```
Doesn't fit in 12GB of RAM.

**Comment by solpeth** [comment]
Yep, that sounds about right. There are other packages that don't quite max out RAM but still eat it up, like `xmobar` and `git-annex`.

The greater the number of flags (and therefore combinations of those flags) and the greater the number of overall dependencies, the more memory and time is consumed.

All I've been able to do so far is parallelise part of the computation and have hackport print a warning.

**Comment by solpeth** [comment]
This is the same as issue #56

**Comment by l29ah** [comment]
Ironically, deepseq-bounded is a dep of a tool that helps finding space leaks.

**Comment by solpeth** [comment]
Very ironic indeed!

If I remember correctly, one way to force the `hackport merge` of `deepseq-bounded` may be to download the `deepseq-bounded` tarball, edit the `.cabal` file so that flags are either hard-enabled or disabled and then generate an ebuild from your hand-edited `.cabal` file.

It's been a while since I've done this, but if the above instructions aren't correct the idea is to disable or hard-enable as many flags as possible so that hackport doesn't compute those huge chains of flag combinations. Keeping the number of conditional flags to about 13 generally means my (old) machine can generate the ebuild within a couple of minutes. I find any increase in the number of flags (which is also affected by the overall number of package dependencies) increases the time taken to complete the task exponentially or even factorially.

Good luck!

I also wonder if there is a solution that can compute in constant space, and how difficult it would be to integrate this solution onto the existing hackport codebase. It wouldn't solve the time delay, but it would be nice not to max out one's RAM.
