### ISSUE TITLE
Should hackport produce `IUSE=""`?

### ISSUE THREAD

**Issue by ezzieyguywuf** [gentoo-haskell/hackport#82]
From the guidance I've received on `#gentoo-dev-help`, it seems that when `IUSE` is empty, it should be left out entirely.

Should we update hackport to do this?

**Comment by solpeth** [comment]
Personally, I use pkgcheck and repoman warnings as the standard on best practice. Specifically pkgcheck is used as the gatekeeper for QA in Gentoo CI. By that metric, given that an empty `IUSE` does not trigger a warning, and I am unaware of plans by the devs to turn empty `IUSE` into actual QA issues, this isn't a question of _correctness_ but rather _stylistic preference_.

At a certain point we became aware that some functionality of hackport (short long descriptions, descriptions matching package names, empty <use> elements in metadata.xml, etc.) was triggering pkgcheck (or rather Gentoo CI) warnings, so we adjusted hackport behaviour. To again use the above metric, it was an issue of correctness rather than style, so it had to be done promptly. There was a tangible benefit to enacting those changes beyond style. And it now seems to not cause any Gentoo CI issues automatically.

If an empty `IUSE` were triggering CI issues then I would see this as something of importance, but otherwise I don't see the point. So, from the perspective of a) avoiding unnecessary effort so as to redirect that effort in more fruitful directions, and b) to avoid changes which don't create concrete benefits, my (informal) vote and advice on this is to leave it be.

Having said that, one can do whatever they like and open a PR to implement this whenever they want, and if devs like the stylistic change they can merge it anyway :) for me, thanks for the food for thought regardless!

**Comment by trofi** [comment]
I think long ago `IUSE` (and a few other variables) were required to be always defined by `repoman`. The decision was reversed snce.

 Gentoo's https://gitweb.gentoo.org/repo/gentoo.git/tree/skel.ebuild#n80 says `IUSE` is optional. I think it's reasonable to generate clean ebuilds if it does not complicate `hackport`'s code (it should not in this case). Do you want to give it a try?

**Comment by ezzieyguywuf** [comment]
> Do you want to give it a try?

Yes, I've been meaning to dig into hackport anyway, I'll take a stab at it.

**Comment by solpeth** [comment]
@ezzieyguywuf: if you're still interested in this, looking at it it may be as simple as a conditional in `Portage.Ebuild.showEbuild` where we use `ss` to print `IUSE="` followed by the USE flags. Could be something like `if null (iuse ebuild) then nl else ss "IUSE="...` etc.

**Comment by ezzieyguywuf** [comment]
> @ezzieyguywuf: if you're still interested in this, looking at it it may be as simple as a conditional in `Portage.Ebuild.showEbuild` where we use `ss` to print `IUSE="` followed by the USE flags. Could be something like `if null (iuse ebuild) then nl else ss "IUSE="...` etc.

Definitely still interested in working on this. Got a bit sidetracked when setting up my dev environment with #1074. I think I'll file something upstream, as L29A (the original poster) suggested. Then I can finally start hacking on hackport lol
